### ISSUE TITLE
Command multi-select

### ISSUE THREAD

**Issue by Crystalwarrior** [AnidemDex/Blockflow#106]
Selecting multiple commands and being able to perform right-click commands on that group, for example selecting like 5 commands and Copying would result in the Paste option pasting them in the same order they were selected.

If there are gaps in selection, it'll just put them closer together on paste.

**Comment by AnidemDex** [comment]
This will require to be able to have multiple selection on the current displayer first

**Comment by Crystalwarrior** [comment]
funny tree moment. I guess more the reason to work out #92
