### ISSUE TITLE
Undo-redo breaks in certain situations, resulting in "can't call <operation> on Nil" errors

### ISSUE THREAD

**Issue by Crystalwarrior** [AnidemDex/Blockflow#107]
very inconsistent, let's document situations where this happens ideally with videos or screenshots attached. Hard to reproduce

**Comment by AnidemDex** [comment]
Is this still happening?

**Comment by AnidemDex** [comment]
Is still valid? Can't replicate

**Comment by AnidemDex** [comment]
@Crystalwarrior a little bump
