### ISSUE TITLE
Add categories for all commands

### ISSUE THREAD

**Issue by Crystalwarrior** [AnidemDex/Blockflow#123]
part of https://github.com/AnidemDex/Blockflow/pull/117, we should now categorize all the existing commands in a convenient way.

Here's the list for reference:
![image](https://github.com/AnidemDex/Blockflow/assets/3470436/7c4606c8-67b5-47ea-b6e6-95a15e373d80)

**Comment by AnidemDex** [comment]
Branch, go-to and return can be under a "Logic" category 🤔

**Comment by Crystalwarrior** [comment]
@AnidemDex how's this? suggested list
![image](https://github.com/AnidemDex/Blockflow/assets/3470436/01b45068-85ba-4d02-8a3e-88ceb78d2bae)

**Comment by AnidemDex** [comment]
Maybe not "manipulation", Others looks good for me
