### ISSUE TITLE
Command List keeps disappearing

### ISSUE THREAD

**Issue by Crystalwarrior** [AnidemDex/Blockflow#129]
![image](https://github.com/AnidemDex/Blockflow/assets/3470436/99bc1a30-c9e3-43d4-9df2-27121433de01)

I believe this started happening since https://github.com/AnidemDex/Blockflow/pull/126
I also noticed adding new custom commands from the project configuration causes it to disappear/reappear as if a timer keeps stacking on top of itself. Are we using a timer???

**Comment by AnidemDex** [comment]
Can replicate. This is probably due

https://github.com/AnidemDex/Blockflow/blob/bd2e06bc0af5641d86b565bff46a00f63781c1d3/core/plugin_script.gd#L122-L123

and
https://github.com/AnidemDex/Blockflow/blob/bd2e06bc0af5641d86b565bff46a00f63781c1d3/core/plugin_script.gd#L163

We update the whole list intermediately after _any_ change. An error happens silently in
https://github.com/AnidemDex/Blockflow/blob/bd2e06bc0af5641d86b565bff46a00f63781c1d3/editor/command_list.gd#L102-L114

So the builder stops and doesn't create anything until is valid or a request for a new rebuild happens.

Maybe we should rebuild only if the specific thing that we need changed (this means we will need some sort of cache to compare with?)

---

I can't replicate the timer thin
