### ISSUE TITLE
For comment command, multiline comments should be ellipsed

### ISSUE THREAD

**Issue by Crystalwarrior** [AnidemDex/Blockflow#21]
In the timeline view it's turned into a one-liner.
![image](https://user-images.githubusercontent.com/3470436/233676737-a48c8646-8936-4bc7-abf2-32ae76d11b04.png)

Potential suggestions:
![image](https://user-images.githubusercontent.com/3470436/233676799-51dd39fa-04b5-43d7-b9fe-c1338e230cd1.png)

or even
![image](https://user-images.githubusercontent.com/3470436/233676829-870927fd-cfb6-4f13-b3ff-65a6a4ddf7bc.png)

**Comment by AnidemDex** [comment]
This also seems like a godot bug. Why is removing new line character and siplaying it in oneline?

**Comment by Crystalwarrior** [comment]
> This also seems like a godot bug. Why is removing new line character and siplaying it in oneline?

I think it's cuz it's a label? No clue. Might just use rich text label for these instead

**Comment by AnidemDex** [comment]
For future reference we can move from Tree to Vbox and HBox stuff as EditorInspector did, but i don't want to do that for now.

We can use `(...)` and show the rest of the string on mouse hover
