### ISSUE TITLE
Things needed to make a 1.0 release

### ISSUE THREAD

**Issue by AnidemDex** [AnidemDex/Blockflow#40]
_Hopefully, before this month (may) ends_
- [x] #20
- [x] #25 
- [x] #36 
- [x] #37 
- [x] #38 
- [x] #39 
- [ ] An scene to try all commands, one by one

**Comment by Crystalwarrior** [comment]
Animate command seems the easiest to get out of the way

**Comment by Crystalwarrior** [comment]
We're very close!

**Comment by AnidemDex** [comment]
There are no examples (yet), but a working repo that crystal use as playground
