### ISSUE TITLE
' is displayed as \' in command hint string

### ISSUE THREAD

**Issue by Crystalwarrior** [AnidemDex/Blockflow#46]
I think it's trying to escape it but fails for some reason
![image](https://github.com/AnidemDex/Godot-CommandTimeline/assets/3470436/b5c3b3dd-31ad-447c-bc5a-db5e51500cb0)

**Comment by AnidemDex** [comment]
Can't replicate on 8b68287 

Maybe is fixed already? 
![image](https://github.com/AnidemDex/Blockflow/assets/7025991/33a72769-aa54-45cc-854f-3ade6c7488d2)
