### ISSUE TITLE
Creating a new command should put it directly after the selected command, if one exists

### ISSUE THREAD

**Issue by Crystalwarrior** [AnidemDex/Blockflow#53]
If a command is selected, put the new command directly after it

**Comment by AnidemDex** [comment]
This is supposed to be fixed by https://github.com/AnidemDex/Blockflow/pull/64 can you confirm?

**Comment by AnidemDex** [comment]
Fixed by [60d7b5f](https://github.com/AnidemDex/Blockflow/pull/72/commits/60d7b5fb4d2198c38f131b9817e3e77f027e1322)
