### ISSUE TITLE
Save a command as a "preset" via context menu for re-use

### ISSUE THREAD

**Issue by Crystalwarrior** [AnidemDex/Blockflow#54]
For example, if you construct a commonly reused "call" command, being able to right-click it and "save preset" would allow you to reuse it in any timeline you need it in (saving all the properties as well). The duplicate command is already halfway there, but this is essentially a quick way to duplicate the command into any timeline.

**Comment by AnidemDex** [comment]
I like this one. This way, with some "group" command, presets of many commands can be reused

**Comment by AnidemDex** [comment]
Update: Now with #54 we can possibly make presets using CommandCollections

**Comment by Crystalwarrior** [comment]
Yo that's clever as hell

**Comment by AnidemDex** [comment]
Update on this, we'll need to make a way to reuse already created command resources, so we can keep these presets (kinda like what `EditorBlock.duplicate` does)

**Comment by AnidemDex** [comment]
Related to  #55

**Comment by AnidemDex** [comment]
Fixed by #145
