### ISSUE TITLE
Where's the documentation?

### ISSUE THREAD

**Issue by AnidemDex** [AnidemDex/Blockflow#82]
@AnidemDex where the duck documentation is at? How Am I even supposed to know how I use this thing?

- [x] Update readme, explaining:
  - [x]  what is this
  - [x]  why this exist
  - [x] how things works (or how can be used, that works too).
- [x] Update internal classes documentation. We know that not all classes has complete documentation.
- [ ] Make a working example. A little game, just a single scene.

Other useful features could be extra documentation files with further explanation about specific parts (like command creation)

**Comment by AnidemDex** [comment]
Still need some images, and a logo

**Comment by Crystalwarrior** [comment]
Another thing that we should do is make web browser based documentation that is generated from GDScript docs, could maybe use https://github.com/GDQuest/gdscript-docs-maker for that task?

**Comment by AnidemDex** [comment]
I have no idea about how to generate web pages

**Comment by AnidemDex** [comment]
Closing, the example will require its own issue
