### ISSUE TITLE
Any changes in the editor uncollapse everything the user collapsed

### ISSUE THREAD

**Issue by Crystalwarrior** [AnidemDex/Blockflow#98]
https://github.com/AnidemDex/Blockflow/assets/3470436/f3cbd0bc-93f3-4285-a704-b4605022aa3e

**Comment by AnidemDex** [comment]
The resource layout can be saved per project in editor layout

**Comment by AnidemDex** [comment]
Ok, so, after a little investigation:

- The layout per resource can be saved under `.godot/editor/collection_layout.cfg` as editor does for scripts under `script_editor_cache.cfg`
- Editor (and not the plugin) loads and saves the layout each time the collection is loaded or changed/closed
- To ensure not making many file operations, each command will keep their layout too while being edited
